# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180827_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
