# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_profile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_ext',
            field=models.CharField(default='cpp', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='bot_path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
