# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-17 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180913_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
